#!/usr/bin/env bash
# dark-matter/open-pr.sh — commits staged cleanup and opens a PR.
#
# Design rules:
#   - Reads `.dark-matter/changes_made`; refuses to open a PR when no
#     changes were made (deterministic no-op instead of an empty PR).
#   - Branch name includes a UTC stamp so reruns don't pile up.
#   - All `git` calls pass `--no-gpg-sign` to avoid prompting in CI.
#   - PR title and body are deterministic.
#   - Never force-pushes.
#
# Usage: bash open-pr.sh
# Env:  GH_TOKEN (required) — the Talos backend resolves this from env or
#       `gh auth token` before invoking.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
DM_DIR="$REPO_ROOT/.dark-matter"

if [ ! -f "$DM_DIR/changes_made" ]; then
  echo "ERROR: $DM_DIR/changes_made missing. Run run.sh first." >&2
  exit 64
fi

if [ "$(cat "$DM_DIR/changes_made")" != "YES" ]; then
  echo "NO_CHANGES: nothing to PR"
  exit 0
fi

if [ -z "${GH_TOKEN:-}" ]; then
  echo "ERROR: GH_TOKEN is required." >&2
  exit 65
fi
export GH_TOKEN

STAMP="$(date -u +%Y%m%d-%H%M)"
BRANCH="chore/dark-matter-${STAMP}"

git -C "$REPO_ROOT" checkout -b "$BRANCH" --no-gpg-sign 2>/dev/null || \
  git -C "$REPO_ROOT" switch -c "$BRANCH"

git -C "$REPO_ROOT" add -A
# Commit only if there is something staged; otherwise exit cleanly.
if git -C "$REPO_ROOT" diff --cached --quiet; then
  echo "NO_CHANGES: nothing staged after git add"
  exit 0
fi

git -C "$REPO_ROOT" commit --no-gpg-sign -m "chore(dark-matter): automated cleanup ${STAMP}"

git -C "$REPO_ROOT" push -u origin "$BRANCH"

PR_URL="$(gh pr create \
  --head "$BRANCH" \
  --title "chore(dark-matter): automated cleanup ${STAMP}" \
  --body "Generated by Talos dark-matter scan on ${STAMP}.

## Why
Automated dead-code and unused-dependency cleanup.

## What changed
See the commit diff. Generated from \`.dark-matter/summary.md\`.

## Validation
Reviewer should confirm CI is green before merge.")"

# Machine-parseable last line for the backend.
echo "PR_URL=$PR_URL"
echo "BRANCH=$BRANCH"
